;-----------------------------------------------------------------------------
; instructions.mac
; ADDITIONAL INSTRUCTION MACROS
; 2018-04-19
;-----------------------------------------------------------------------------
.IF !.DEFINEDMACRO(MVA)		;DON'T DEFINE MACROS IF THEY EXIST ALREADY

;-----------------------------------------------------------------------------
; MOVE BYTE USING ACCUMULATOR
;-----------------------------------------------------------------------------
.MACRO MVA VAL, ADDR
	LDA VAL
	STA ADDR
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE WORD USING ACCUMULATOR
;-----------------------------------------------------------------------------
.MACRO MWA SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDA #<(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STA DEST
		LDA #>(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STA 1+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDA SRC
		STA DEST
		LDA 1+SRC
		STA 1+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE DWORD USING ACCUMULATOR
;-----------------------------------------------------------------------------
.MACRO MDA SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDA #.LOBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STA DEST
		LDA #.HIBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STA 1+DEST
		LDA #.LOBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STA 2+DEST
		LDA #.HIBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STA 3+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDA SRC
		STA DEST
		LDA 1+SRC
		STA 1+DEST
		LDA 2+SRC
		STA 2+DEST
		LDA 3+SRC
		STA 3+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE BYTE USING X REGISTER
;-----------------------------------------------------------------------------
.MACRO MVX VAL, ADDR
	LDX VAL
	STX ADDR
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE WORD USING X REGISTER
;-----------------------------------------------------------------------------
.MACRO MWX SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDX #<(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STX DEST
		LDX #>(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STX 1+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDX SRC
		STX DEST
		LDX 1+SRC
		STX 1+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE DWORD USING X REGISTER
;-----------------------------------------------------------------------------
.MACRO MDX SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDX #.LOBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STX DEST
		LDX #.HIBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STX 1+DEST
		LDX #.LOBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STX 2+DEST
		LDX #.HIBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STX 3+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDX SRC
		STX DEST
		LDX 1+SRC
		STX 1+DEST
		LDX 2+SRC
		STX 2+DEST
		LDX 3+SRC
		STX 3+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE BYTE USING Y REGISTER
;-----------------------------------------------------------------------------
.MACRO MVY VAL, ADDR
	LDY VAL
	STY ADDR
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE WORD USING Y REGISTER
;-----------------------------------------------------------------------------
.MACRO MWY SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDY #<(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STY DEST
		LDY #>(.RIGHT (.TCOUNT ({SRC})-1, {SRC}))
		STY 1+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDY SRC
		STY DEST
		LDY 1+SRC
		STY 1+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; MOVE DWORD USING Y REGISTER
;-----------------------------------------------------------------------------
.MACRO MDY SRC, DEST
	.IF (.MATCH (.LEFT (1, {SRC}), #))			;IMMEDIATE MODE
		LDY #.LOBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STY DEST
		LDY #.HIBYTE(.LOWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STY 1+DEST
		LDY #.LOBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STY 2+DEST
		LDY #.HIBYTE(.HIWORD(.RIGHT (.TCOUNT ({SRC})-1, {SRC})))
		STY 3+DEST
	.ELSE							;ASSUME ABSOLUTE OR ZERO PAGE
		LDY SRC
		STY DEST
		LDY 1+SRC
		STY 1+DEST
		LDY 2+SRC
		STY 2+DEST
		LDY 3+SRC
		STY 3+DEST
	.ENDIF
.ENDMACRO

;-----------------------------------------------------------------------------
; ADD WITHOUT CARRY
;-----------------------------------------------------------------------------
.MACRO ADD VAL
	CLC
	ADC VAL
.ENDMACRO


.MACRO PUSH_AXY
	PHA		; PUSH ACCUMULATOR TO STACK
	PHX		; PUSH X TO STACK
	PHY		; PUSH Y TO STACK
.ENDMACRO

.MACRO PULL_AXY
	PLY		; PULL Y FROM STACK
	PLX		; PULL X FROM STACK
	PLA		; PULL A FROM STACK
.ENDMACRO

.MACRO PUSH_AX
	PHA
	PHX
.ENDMACRO

.MACRO PULL_AX
	PLX
	PLA
.ENDMACRO

.MACRO PUSH_AY
	PHA
	PHY
.ENDMACRO

.MACRO PULL_AY
	PLY
	PLA
.ENDMACRO


.ENDIF
