;-----------------------------------------------------------------------------
; FAT.MAC
; PROCEDURE CALL MACROS FOR THE FAT16 DRIVER
; 2018-05-09
;-----------------------------------------------------------------------------
.IFNDEF FAT_INIT

.INCLUDE "INSTRUCTIONS.MAC"
.INCLUDE "MOVE.MAC"
.INCLUDE "MATH_32.MAC"
.INCLUDE "CFDRIVER.MAC"

.IMPORT FAT_INIT, FAT_FIND, FAT_LOAD
.IMPORT FILENAME, FILESIZE, FILEDEST, FAT_STATUS, FAT_ERROR

;-----------------------------------------------------------------------------
; FS_INIT
; FIND A FAT16 PARTITION AND INITIALIZE THE DRIVER
;-----------------------------------------------------------------------------
.MACRO FS_INIT
	JSR FAT_INIT
.ENDMACRO

;-----------------------------------------------------------------------------
; FS_LOAD
; FNAME: 11-BYTE FAT16 FILENAME (8.3 FORMAT WITHOUT THE DOT)
; FDEST: DESTINATION ADDRESS TO LOAD THE FILE TO
; DESTSIZE: MAXIMUM SIZE THAT CAN BE LOADED TO THE DESTINATION ADDRESS
;-----------------------------------------------------------------------------
.MACRO FS_LOAD FNAME, FDEST, DESTSIZE
	.IFNBLANK FNAME
		MOVE FNAME, FILENAME, #$0B					;COPY THE FILENAME FROM A MEMORY LOCATION
		JSR FAT_FIND
		LDA FAT_STATUS
		BEQ GOOD_FNAME
		JMP FAT_ERROR
		GOOD_FNAME:
	.ENDIF
	.IFNBLANK FDEST
		PHA
		MWA #FDEST, FILEDEST
		PLA
	.ENDIF
	JSR FAT_LOAD
	LDA FAT_STATUS
	BEQ GOOD_LOAD
	JMP FAT_ERROR
	GOOD_LOAD:
.ENDMACRO

.ENDIF
