;-----------------------------------------------------------------------------
; MATH_32.MAC
; PROCEDURE CALL MACROS FOR THE MATH_32 LIBRARY
; ADAPTED FROM HTTPS://GITHUB.COM/MAIKMERTEN/TINYLOAD
; 2018-04-20
;-----------------------------------------------------------------------------
.IFNDEF MATH_ADD32	;DON'T DEFINE MACROS IF THEY EXIST ALREADY

.INCLUDE "INSTRUCTIONS.MAC"
.IMPORT MATH_ADD32, MATH_SUB32, MATH_MUL32, MATH_DIV32
.IMPORTZP M32PTR1, M32PTR2, M32PTR3, M32PTR4

;-----------------------------------------------------------------------------
; ADD32 - 32-BIT ADDITION USING POINTERS TO 32-BIT VARIABLES
; SRC1 + SRC2 = DEST
;-----------------------------------------------------------------------------
.MACRO ADD32 SRC1, SRC2, DEST
	PHA
	.IFNBLANK SRC1
	MWA SRC1, M32PTR1
	.ENDIF
	.IFNBLANK SRC2
	MWA SRC2, M32PTR2
	.ENDIF
	.IFNBLANK DEST
	MWA DEST, M32PTR3
	.ENDIF
	PLA
	JSR MATH_ADD32
.ENDMACRO

;-----------------------------------------------------------------------------
; SUB32 - 32-BIT SUBTRACTION USING POINTERS TO 32-BIT VARIABLES
; SRC1 - SRC2 = DEST
;-----------------------------------------------------------------------------
.MACRO SUB32 SRC1, SRC2, DEST
	PHA
	.IFNBLANK SRC1
	MWA SRC1, M32PTR1
	.ENDIF
	.IFNBLANK SRC2
	MWA SRC2, M32PTR2
	.ENDIF
	.IFNBLANK DEST
	MWA DEST, M32PTR3
	.ENDIF
	PLA
	JSR MATH_SUB32
.ENDMACRO

;-----------------------------------------------------------------------------
; MUL32 - 32-BIT MULTIPLICATION USING POINTERS TO 32-BIT VARIABLES
; SRC1 * SRC2 = DEST
;-----------------------------------------------------------------------------
.MACRO MUL32 SRC1, SRC2, DEST
	PHA
	.IFNBLANK SRC1
	MWA SRC1, M32PTR1
	.ENDIF
	.IFNBLANK SRC2
	MWA SRC2, M32PTR2
	.ENDIF
	.IFNBLANK DEST
	MWA DEST, M32PTR3
	.ENDIF
	PLA
	JSR MATH_MUL32
.ENDMACRO

;-----------------------------------------------------------------------------
; DIV32 - 32-BIT DIVISION USING POINTERS TO 32-BIT VARIABLES
; SRC1 / SRC2 = DEST1
; REMAINDER DEST2
;-----------------------------------------------------------------------------
.MACRO DIV32 SRC1, SRC2, DEST1, DEST2
	PHA
	.IFNBLANK SRC1
	MWA SRC1, M32PTR1
	.ENDIF
	.IFNBLANK SRC2
	MWA SRC2, M32PTR2
	.ENDIF
	.IFNBLANK DEST1
	MWA DEST1, M32PTR3
	.ENDIF
	.IFNBLANK DEST2
	MWA DEST2, M32PTR4
	.ENDIF
	PLA
	JSR MATH_DIV32
.ENDMACRO

.ENDIF
